import type { IMessage } from "./types/message";

const einsteinQuotes = [
  "Imagination is more important than knowledge.",
  "The only source of knowledge is experience.",
  "A person who never made a mistake never tried anything new.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
];

const newtonQuotes = [
  "If I have seen further, it is by standing on the shoulders of giants.",
  "To every action, there is always opposed an equal reaction.",
  "We build too many walls and not enough bridges.",
  "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.",
  "I can calculate the motion of heavenly bodies, but not the madness of people.",
];

const darwinQuotes = [
  "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.",
  "A man who dares to waste one hour of time has not discovered the value of life.",
  "I love fools' experiments. I am always making them.",
  "We can allow satellites, planets, suns, universe, nay whole systems of universes, to be governed by laws, but the smallest insect, we wish to be created at once by special act.",
];

const loremIpsumList = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Vestibulum a nunc in mi blandit accumsan vel ut nunc.",
  "Pellentesque aliquet arcu eget ullamcorper consectetur.",
  "Phasellus mollis nisi eu pretium condimentum.",
  "Proin et massa ac lorem ultricies vestibulum.",
  "Integer facilisis neque egestas elit pretium, quis aliquam eros pharetra.",
  "Vivamus ut metus vitae ex iaculis placerat et nec elit.",
  "Duis sodales sem non diam egestas varius.",
  "Nunc lobortis erat quis pharetra condimentum.",
  "Nullam dictum dui id hendrerit euismod.",
  "Fusce vel lectus a ipsum dapibus consectetur ut ac felis.",
  "Sed sagittis ante viverra, tristique ante at, venenatis dolor.",
  "Curabitur id arcu egestas, suscipit diam sed, varius quam.",
  "Pellentesque pellentesque nulla ac massa accumsan laoreet.",
  "Curabitur sed quam maximus, faucibus eros sit amet, eleifend ligula.",
  "Nulla commodo lectus et urna elementum, hendrerit vestibulum mi convallis.",
  "Nulla scelerisque purus eu nulla egestas vehicula.",
  "Cras maximus mi sit amet dolor tristique iaculis.",
  "Phasellus convallis augue sed neque hendrerit lobortis.",
  "Sed id risus bibendum, bibendum turpis ac, placerat neque.",
  "Proin ornare erat et vestibulum pellentesque.",
  "Vestibulum accumsan leo luctus iaculis tempor.",
  "Nunc nec arcu eu urna venenatis placerat.",
  "Pellentesque mattis lectus ac nisi tempus lobortis.",
  "Curabitur blandit tortor at lorem feugiat sollicitudin.",
  "Mauris tincidunt nunc vitae lacus molestie ultrices.",
  "Aenean ut nisi ut nisl semper congue sit amet ut est.",
  "Curabitur in enim ut libero dignissim dapibus.",
  "Sed sollicitudin risus a accumsan venenatis.",
  "Curabitur lobortis leo et risus vehicula, sed maximus sem fermentum.",
  "Donec pretium ante ut dolor fermentum, eu fringilla diam eleifend.",
  "Donec consectetur felis a dui laoreet, eu porttitor massa ullamcorper.",
  "Duis eleifend dolor in tortor pretium, ac luctus mauris scelerisque.",
  "Nam blandit magna in turpis porta facilisis.",
  "Duis non tortor at risus auctor pellentesque in a tortor.",
  "Phasellus vestibulum ligula nec mi congue, et convallis elit dapibus.",
  "Sed sed augue et sem facilisis tincidunt ac vitae sem.",
  "Ut sed arcu et nulla consequat suscipit.",
  "Etiam feugiat risus sed mattis volutpat.",
  "Cras sit amet est tempus odio luctus sollicitudin.",
  "Aliquam viverra risus id vulputate cursus.",
  "Vivamus eleifend elit ac sagittis tincidunt.",
  "Morbi quis nulla tincidunt, aliquet ex et, ullamcorper lectus.",
  "Proin sit amet nulla vitae enim interdum egestas.",
  "Curabitur dapibus sem in diam vehicula pretium.",
  "Nam vel elit eu metus vehicula egestas.",
  "Nullam posuere mauris sed laoreet gravida.",
  "Mauris ac elit dignissim, dapibus lacus in, luctus urna.",
  "Etiam vehicula neque id nunc tincidunt ullamcorper.",
  "Pellentesque non sem nec lorem dictum venenatis.",
  "Donec quis purus vel mi dignissim tincidunt.",
  "Praesent et ipsum in purus molestie efficitur.",
  "Pellentesque sit amet nulla eget lacus porttitor laoreet quis at augue.",
  "Phasellus non eros consectetur, dapibus quam vitae, pharetra odio.",
  "Etiam vehicula mauris eu lectus elementum eleifend.",
  "Vivamus a neque sit amet lacus volutpat congue.",
  "Proin feugiat neque in lectus tincidunt, sit amet faucibus odio fringilla.",
  "Proin feugiat libero et urna lobortis condimentum.",
  "Cras et neque suscipit, pretium massa tincidunt, aliquam quam.",
  "Proin et tortor sed justo aliquet tempus.",
  "Aliquam laoreet ipsum id lorem ullamcorper scelerisque.",
  "Phasellus tempus magna sit amet libero placerat, eu euismod sem sagittis.",
  "Duis et arcu ut urna rutrum condimentum.",
  "Donec consectetur nisi non velit ullamcorper aliquet.",
  "Duis pretium felis sit amet massa gravida rutrum.",
  "Aenean eleifend mi vel ante eleifend semper.",
  "Sed id nunc eget ante dapibus pulvinar non id nisl.",
  "Fusce accumsan est et tempor dignissim.",
  "Etiam in ligula fermentum, semper tellus id, blandit est.",
  "Morbi eget metus molestie, congue orci non, pharetra diam.",
  "Aliquam ultricies est sit amet pellentesque finibus.",
  "Fusce at nisl ac quam feugiat luctus non nec est.",
  "Curabitur dictum augue sed tellus sollicitudin, quis ultricies sem fringilla.",
  "Etiam eget lorem vel urna dictum fermentum vel at magna.",
  "Aenean eu lorem quis diam mattis sodales.",
  "Morbi quis enim ac ipsum vestibulum efficitur id ac urna.",
  "In venenatis sem eu odio luctus tempor.",
  "Cras scelerisque tellus vel nisl elementum dictum.",
  "Ut lacinia mauris blandit, fringilla est sed, sagittis nulla.",
  "Aenean aliquam arcu sed urna pellentesque consectetur.",
  "Maecenas porttitor augue luctus imperdiet fermentum.",
  "Aliquam in orci ut turpis luctus ullamcorper.",
  "Pellentesque et est vestibulum dolor iaculis egestas.",
  "Etiam bibendum sapien vel metus rutrum pharetra.",
  "Ut lacinia mauris ac neque tristique volutpat.",
  "Nam ut metus posuere, auctor urna eget, vulputate dui.",
  "Nunc laoreet ipsum vel tortor pellentesque, quis imperdiet sapien pulvinar.",
  "Etiam hendrerit est vitae leo egestas sagittis.",
  "Aenean eu arcu sit amet purus tincidunt egestas eget iaculis nisi.",
  "Ut ac lorem non justo ornare pharetra et ac leo.",
  "Morbi eu nulla id ipsum ornare tempor in pretium odio.",
  "Nulla et nisi cursus, ultrices elit quis, porta ipsum.",
  "Maecenas nec purus vel ex volutpat luctus vel vel mauris.",
  "Nulla sit amet dui id nibh faucibus egestas.",
  "Curabitur nec nibh et erat tempor iaculis.",
  "Sed sed nulla vitae ante porta fringilla id at urna.",
  "Donec ac nulla at metus dignissim convallis.",
  "Sed fringilla eros sed orci elementum ultrices vitae ac libero.",
  "Integer eleifend dolor ut luctus mollis.",
  "Quisque elementum sapien ac volutpat vehicula.",
  "Maecenas eu metus sit amet nisl iaculis vulputate ac quis tortor.",
  "Vestibulum non tortor eu augue commodo aliquam.",
  "Nulla sit amet leo sed lorem aliquet efficitur.",
  "Mauris eu nisl quis sapien finibus euismod vitae vel augue.",
  "Aliquam eget turpis at dui condimentum mollis sit amet sit amet est.",
  "Integer malesuada justo nec laoreet venenatis.",
  "Suspendisse mattis tortor eget sem tristique convallis.",
  "Vestibulum mattis ligula et aliquet molestie.",
  "Donec congue leo sed massa dignissim hendrerit.",
  "In vitae velit non felis cursus vehicula.",
  "Nullam bibendum ex eu lorem laoreet aliquet.",
  "Morbi ut elit vitae odio pulvinar venenatis.",
  "Etiam et elit tincidunt mauris hendrerit ornare.",
  "Nam eget urna dignissim, laoreet nibh id, gravida mi.",
  "Sed sagittis metus ac lorem consequat elementum.",
  "Nulla id lectus in ligula suscipit placerat at vel libero.",
  "Quisque facilisis ex et tortor vehicula dignissim.",
  "Nulla a quam porta, mattis augue id, placerat elit.",
  "Vivamus ac orci in enim dapibus hendrerit at non neque.",
  "Cras auctor leo nec purus imperdiet, vel auctor est fringilla.",
  "Integer rutrum ex mollis placerat consectetur.",
  "Aliquam rhoncus dolor sit amet ex volutpat, porttitor volutpat ante condimentum.",
  "Cras porttitor justo in ex finibus, ut mollis elit pulvinar.",
  "Nullam sodales libero ut vulputate dignissim.",
  "In vel felis sit amet nunc venenatis mattis.",
  "Nunc pretium felis nec dui elementum mattis.",
  "Duis scelerisque erat eget lobortis sollicitudin.",
  "Quisque quis enim id mauris laoreet faucibus at vel dolor.",
  "Nunc ut ligula laoreet, rhoncus lacus sit amet, commodo purus.",
  "Nunc vehicula velit ut justo fermentum porttitor.",
  "Praesent sodales nulla at odio vulputate, in tempor erat rutrum.",
  "Aliquam sagittis nisl id leo vulputate, et facilisis nisl condimentum.",
  "Nullam pretium dui non est molestie, quis maximus est porta.",
  "In sodales diam eu ex semper sodales.",
  "Nam finibus justo nec sodales tincidunt.",
  "In accumsan lorem vitae eros congue, vel hendrerit purus pellentesque.",
  "Proin a sapien porttitor, lacinia arcu tempus, viverra metus.",
  "Aliquam ac odio et eros sodales efficitur a id leo.",
  "Suspendisse pharetra erat id sem feugiat, et lacinia elit feugiat.",
  "Pellentesque posuere dui non posuere dictum.",
  "Duis sit amet lectus efficitur, porttitor metus vitae, maximus diam.",
  "Morbi maximus magna a odio mollis viverra.",
  "Proin et tortor pharetra, vehicula urna sed, vulputate lectus.",
  "Quisque non lectus varius, bibendum neque at, ornare augue.",
  "Cras ultrices quam quis consectetur tincidunt.",
  "Fusce porta dui nec sollicitudin consectetur.",
  "Aliquam sit amet ante ut leo gravida tempor ut fringilla orci.",
  "Sed sit amet nisl sed orci feugiat rutrum.",
  "Mauris in odio venenatis, varius metus eget, ultrices tortor.",
  "Nam sit amet tellus eget tellus malesuada pulvinar.",
  "Suspendisse sit amet libero placerat, gravida nisi eu, venenatis orci.",
  "Vestibulum aliquet elit sed ex dictum aliquam.",
  "Curabitur ac purus at dui lacinia mattis eget ac nisi.",
  "Proin scelerisque justo a viverra bibendum.",
  "Cras at dui in nunc tincidunt consequat vel id augue.",
  "Duis quis purus consectetur, vehicula mi vel, commodo purus.",
  "Praesent eu orci in magna mollis sagittis ut id arcu.",
  "Etiam vel lacus sed ex tristique egestas.",
  "Sed commodo nisl nec leo interdum posuere.",
  "Donec imperdiet ante ac lectus ullamcorper efficitur.",
  "Cras vel erat vel est eleifend porta sit amet at risus.",
  "Quisque egestas dui eget tortor tempor scelerisque.",
  "Nullam pharetra nunc et odio varius mollis.",
  "Nulla id sem convallis, placerat nulla a, efficitur arcu.",
  "Praesent mattis arcu vel enim dapibus vulputate.",
  "Aenean ac metus non leo aliquet dapibus.",
  "Nam dictum lacus nec imperdiet aliquet.",
  "Nam mattis nunc sed sem fermentum sodales.",
  "Aenean vitae nulla vel justo blandit scelerisque sed a nisl.",
  "Nulla placerat erat non leo sollicitudin posuere.",
  "Donec eget nisl luctus, aliquet est sit amet, porttitor augue.",
  "Vivamus congue erat quis ipsum volutpat, nec molestie mauris pharetra.",
  "In non elit eget ex volutpat luctus at ac est.",
  "Vestibulum at ex at mauris consectetur ullamcorper vitae sit amet nunc.",
  "Nunc ut quam in felis mollis porttitor scelerisque in est.",
  "Curabitur vitae diam tempus felis interdum condimentum.",
  "Duis vel diam eget metus malesuada porta.",
  "Cras feugiat leo et venenatis feugiat.",
  "Nulla et sapien pellentesque, sagittis augue a, faucibus orci.",
  "Integer eu sapien vel arcu tempor elementum.",
  "In at ex feugiat, vehicula massa at, luctus urna.",
  "Praesent quis tellus ut magna porta convallis quis sit amet nisl.",
  "Etiam ac metus vulputate, porttitor tortor sit amet, feugiat nibh.",
  "Aenean sit amet nibh facilisis, tincidunt libero non, dictum enim.",
  "Ut eu sapien faucibus, varius erat at, porttitor lectus.",
  "Phasellus volutpat felis vitae suscipit mattis.",
  "Integer eget dolor at ante bibendum porta.",
  "Nam at neque at velit dignissim rutrum.",
  "Mauris bibendum ex non erat ullamcorper aliquam.",
  "Sed venenatis justo nec commodo aliquet.",
  "Mauris sodales dolor ac massa eleifend, a hendrerit erat facilisis.",
  "Vivamus fermentum nunc vel mi posuere porttitor.",
  "Aliquam euismod eros vitae mauris molestie, quis elementum tellus tempus.",
  "In tristique ex eu commodo ullamcorper.",
  "Nunc euismod turpis semper ante rhoncus, eu bibendum leo convallis.",
  "Sed luctus erat sit amet velit pellentesque rhoncus.",
  "Integer pretium mi ut finibus tempus.",
  "Aenean quis neque eu eros tempor aliquam ac non orci.",
  "Donec eu est cursus mauris lacinia porttitor.",
  "Vestibulum rhoncus nisi non est semper ultricies.",
  "Duis vehicula ante quis arcu rhoncus, auctor ultricies massa feugiat.",
  "Vivamus facilisis lorem sit amet magna dapibus eleifend.",
  "Nulla non ipsum sed mi scelerisque dapibus.",
  "Praesent gravida tortor at arcu convallis, sit amet dapibus lacus interdum.",
  "Duis ultricies nibh eu arcu bibendum porttitor.",
  "Mauris pretium nibh eu commodo fringilla.",
  "Etiam a magna mattis metus iaculis imperdiet non eu purus.",
  "Proin sed arcu laoreet, ultrices dolor sit amet, ornare nulla.",
  "Nulla iaculis quam ut orci accumsan, semper convallis nisi elementum.",
  "Integer tempor ligula in nulla iaculis consectetur.",
  "Nam nec lacus ut mi iaculis tincidunt eu et enim.",
  "Integer bibendum quam quis sem facilisis dapibus.",
  "Ut vel dui eu ligula accumsan hendrerit.",
  "In hendrerit elit id venenatis consequat.",
  "Praesent venenatis magna id enim fermentum consectetur.",
  "Nulla eu tortor quis felis pellentesque semper.",
  "Duis ut purus ac sapien consequat tristique.",
  "Suspendisse eget velit eu turpis fringilla vehicula a nec neque.",
  "Nam a dolor et sapien tincidunt venenatis quis dapibus odio.",
  "Phasellus interdum dui quis porttitor lacinia.",
  "Nulla sit amet erat gravida, suscipit metus ac, feugiat lectus.",
  "Nulla euismod nisl et dolor lobortis, non pharetra nibh dapibus.",
  "Quisque ac felis malesuada, elementum lacus quis, venenatis urna.",
  "Praesent ut massa vitae sapien mattis dignissim in a elit.",
  "Aliquam eget urna sit amet ipsum posuere pharetra vel vel turpis.",
  "Maecenas semper diam in placerat pretium.",
  "Vestibulum tempor felis a viverra accumsan.",
  "Sed vitae urna molestie, vehicula lorem quis, auctor ligula.",
  "Vivamus congue ante nec metus blandit gravida.",
  "Vestibulum rutrum turpis in cursus volutpat.",
  "Etiam accumsan nisi sed nulla fermentum, a scelerisque mauris malesuada.",
  "Proin vel augue lacinia, viverra nibh quis, imperdiet elit.",
  "Phasellus dictum ante vel suscipit tristique.",
  "Sed aliquet tellus in nibh accumsan, egestas viverra dolor pulvinar.",
  "Phasellus commodo velit eget justo porta, vel porttitor justo viverra.",
  "Sed venenatis tellus eget tincidunt ultricies.",
  "Mauris tincidunt turpis quis eros cursus, vel tempor dui vestibulum.",
  "Aliquam bibendum libero sodales hendrerit ullamcorper.",
  "Nam ut magna eu felis hendrerit aliquet quis ac justo.",
  "Mauris vel diam quis urna lacinia imperdiet.",
  "Integer maximus mi sit amet metus maximus tristique.",
  "Nullam a elit sit amet quam molestie porttitor.",
  "Integer porttitor odio nec risus pharetra, quis porta nunc rutrum.",
  "Quisque sed lectus id augue sodales varius a nec tellus.",
  "Sed eget ex quis mi viverra finibus non vitae ante.",
  "Vestibulum interdum velit nec arcu efficitur rhoncus.",
  "Nulla non massa fermentum, aliquam nisi id, ornare tortor.",
  "In ac felis in metus pharetra aliquam in vitae justo.",
  "Morbi aliquam felis ut mauris convallis, et accumsan urna fringilla.",
  "Nunc viverra elit eu magna venenatis, vel porta risus laoreet.",
  "Morbi lacinia arcu non odio gravida, nec rutrum dui porta.",
  "Cras sed dolor nec sapien porttitor pellentesque et dapibus nisl.",
  "In et sem eget dui venenatis fringilla at quis felis.",
  "Proin consequat mi id nibh malesuada, eget dignissim orci facilisis.",
  "Ut sit amet erat ornare est dignissim pellentesque.",
  "Donec non libero ut lacus aliquet dapibus ut sit amet odio.",
  "Vestibulum porttitor velit eget consequat luctus.",
  "Nullam eu sapien aliquam, dapibus ligula ut, egestas ante.",
  "Curabitur mattis eros eu nisi suscipit varius.",
  "Integer in libero porttitor, hendrerit eros a, vestibulum ante.",
  "Integer sit amet tortor at ante aliquet blandit.",
  "Pellentesque sed odio id eros efficitur mattis.",
  "Fusce vitae mauris sodales, venenatis lectus sit amet, congue urna.",
  "Fusce vitae tellus eu massa maximus aliquam sed sit amet urna.",
  "Nam pharetra enim posuere semper egestas.",
  "Sed efficitur nisl sit amet tortor eleifend, sed congue magna convallis.",
  "Sed ultrices nibh ut enim vehicula tristique.",
  "Nunc ornare massa vitae arcu hendrerit pellentesque.",
  "Nam vitae nunc nec eros elementum fringilla eu ac est.",
  "Quisque et massa condimentum quam facilisis consectetur id a tellus.",
  "Vestibulum non diam consectetur, varius leo eu, maximus enim.",
  "Nunc aliquet sapien nec maximus malesuada.",
  "Vestibulum ultrices sapien ac mi efficitur dapibus.",
  "Nam varius velit eget ligula pellentesque, in lacinia orci vehicula.",
  "Praesent rutrum nunc eget consectetur viverra.",
  "Praesent id augue ut lectus ultricies malesuada.",
  "Mauris ac turpis sed dolor fringilla ornare.",
  "Ut in lectus sit amet velit pellentesque semper.",
  "Etiam euismod ex eget massa ultricies dapibus.",
  "Aliquam pharetra quam sit amet auctor interdum.",
  "Proin maximus purus at aliquam dignissim.",
  "Suspendisse ut sem et metus lobortis gravida.",
  "Morbi posuere neque ut velit accumsan fermentum nec a quam.",
  "Cras ac turpis sit amet tortor hendrerit finibus.",
  "Integer et sapien ac dolor varius laoreet.",
  "Phasellus pellentesque urna sit amet orci condimentum, sed finibus dui convallis.",
  "Proin maximus purus non volutpat scelerisque.",
  "Donec pulvinar urna nec tellus euismod, eget pretium lectus sollicitudin.",
  "Pellentesque et enim euismod, semper felis eget, tempus sapien.",
  "Suspendisse ultricies orci non tellus porttitor sagittis.",
  "Nunc porta purus sit amet augue feugiat, ac viverra odio lobortis.",
  "Vivamus posuere arcu in aliquet bibendum.",
  "Quisque vitae mauris pellentesque, hendrerit urna a, euismod sapien.",
  "Cras in magna eget ligula semper consequat faucibus ut lacus.",
  "Cras non nisi elementum enim vulputate ultrices in nec elit.",
  "Fusce at magna tristique diam laoreet elementum et nec arcu.",
  "Donec feugiat turpis non augue iaculis, sed volutpat nisi accumsan.",
  "Curabitur consequat tortor et eros fringilla tincidunt vitae ut augue.",
  "Sed gravida libero et consectetur dignissim.",
  "Curabitur blandit augue at odio bibendum, ultricies pharetra mi aliquam.",
  "Proin imperdiet nunc ut mauris fringilla euismod.",
  "Nulla et erat consequat, mattis elit et, consequat urna.",
  "Praesent sit amet purus vel leo vulputate porttitor.",
  "Duis sit amet dui vel nisl sodales iaculis quis non turpis.",
  "Sed et nisl auctor, viverra turpis quis, venenatis magna.",
  "Proin ut nunc pretium elit semper tempus.",
  "Maecenas iaculis nibh a sapien blandit, vel vulputate ipsum laoreet.",
  "Etiam ullamcorper ligula nec ullamcorper imperdiet.",
  "Maecenas sollicitudin purus eget purus bibendum, vitae ullamcorper metus vehicula.",
  "Integer quis lectus malesuada elit tempor gravida eu et mauris.",
  "Donec lobortis ipsum vehicula quam fermentum, eu consectetur lacus gravida.",
  "Praesent rutrum dolor quis mauris commodo blandit.",
  "Cras et libero vitae libero consequat egestas eu in risus.",
  "Nulla a metus vel diam malesuada consequat.",
  "In tempus sem vel tincidunt faucibus.",
  "Cras sed nulla ultrices, dignissim sapien vel, aliquam tellus.",
  "Curabitur et augue vulputate, cursus odio eget, pellentesque lacus.",
  "Etiam eget erat mollis, malesuada libero ut, molestie tellus.",
  "Suspendisse fringilla neque quis diam feugiat pretium.",
  "Quisque mollis nisl vitae lacinia malesuada.",
  "Praesent tempor ante quis augue sollicitudin pulvinar.",
  "Integer interdum nulla ac molestie fringilla.",
  "Duis sed lacus in est hendrerit condimentum non vitae tortor.",
  "Integer tempor mi nec turpis pretium eleifend.",
  "Nam ac arcu vel odio ultrices convallis.",
  "Nulla nec nisi feugiat, sollicitudin tortor eget, lobortis mauris.",
  "Donec varius dolor a congue porttitor.",
  "Nunc id tortor semper, facilisis ligula at, malesuada nisl.",
  "Curabitur sagittis est at dui tincidunt, venenatis luctus arcu gravida.",
  "Duis sed arcu fringilla, fermentum lectus nec, cursus leo.",
  "Sed lacinia dui ut lectus imperdiet suscipit.",
  "Cras hendrerit elit sed auctor fringilla.",
  "Nunc sed velit sed elit ultrices feugiat.",
  "Maecenas scelerisque erat eget posuere pellentesque.",
  "Quisque porta justo id nunc commodo scelerisque.",
  "Etiam eget ex vel nulla ullamcorper viverra.",
  "Donec auctor lacus eu nisi posuere, vitae convallis mauris varius.",
  "Quisque at est ut tortor imperdiet rutrum.",
  "Proin sit amet elit bibendum, vehicula nisi id, lobortis odio.",
  "Praesent dictum nisi ac felis finibus, pharetra imperdiet sem porta.",
  "Phasellus aliquam felis sit amet dapibus sodales.",
  "Pellentesque sit amet risus rutrum, tempus enim quis, consectetur lorem.",
  "Aliquam pulvinar augue consequat tempus consequat.",
  "Curabitur efficitur est id sodales viverra.",
  "Aenean vel orci maximus tellus ultricies venenatis.",
];

const solvay = {
  id: "e3abec07-cb2f-4159-af0b-52262ff0552b",
  avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Solvay_conference_1927_%28color%29.jpg/800px-Solvay_conference_1927_%28color%29.jpg?20151227012245",
  name: "Solvay Conference",
};

const einstein = {
  id: "69007cbf-60fb-44b2-80e8-6beaaf6d50f1",
  avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/450px-Albert_Einstein_Head.jpg",
  name: "Albert Einstein",
};

const newton = {
  id: "42f7ebaa-01f7-4df2-b8fd-ace2baa43fe9",
  avatar: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTGNBuKZS2dQ8gViURYxqj0ih63BJgwf4e1KAPzMc1AyYVjDkc_",
  name: "Isaac Newton",
};

const darwin = {
  id: "b6b2cfd1-46cb-4329-8584-91565282c06f",
  avatar: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-79035252.jpg",
  name: "Charles Darwin",
};

export const exampleContacts = [
  solvay,
  einstein,
  newton,
  darwin,
];

export const exampleMessages: IMessage[] = [
  ...einsteinQuotes.map<IMessage>((message, index) => ({
    id: "message-from-einstein-" + index,
    content: message,
    roomId: einstein.id,
    authorId: einstein.id,
    timestamp: 1698647224874 + index * 5 * 60000,
    status: "read",
  })),
  ...newtonQuotes.map<IMessage>((message, index) => ({
    id: "message-from-newton-" + index,
    content: message,
    roomId: newton.id,
    authorId: newton.id,
    timestamp: 1698547224874 + index * 5 * 60000,
    status: "read",
  })),
  ...darwinQuotes.map<IMessage>((message, index) => ({
    id: "message-from-darwin-" + index,
    content: message,
    roomId: darwin.id,
    authorId: darwin.id,
    timestamp: 1698447224874 + index * 5 * 60000,
    status: "read",
  })),
  ...loremIpsumList.map<IMessage>((message, index) => ({
    id: "solvay-conference-message-" + index,
    content: message,
    roomId: solvay.id,
    authorId: (index % 5) % 2 === 0 ? einstein.id : "d51a780b-90ed-4a42-b6f1-df031f1411b5",
    timestamp: 1698647224874 + index * 5 * 60000,
    status: "read",
  })),
];

export function getContactAvatar(contactId: string) {
  switch (contactId) {
    case solvay.id:
      return solvay.avatar;
    case einstein.id:
      return einstein.avatar;
    case newton.id:
      return newton.avatar;
    case darwin.id:
      return darwin.avatar;
    default:
      return "https://picsum.photos/id/237/200/200";
  }
}

export function getContactName(contactId: string, defaultName: string) {
  switch (contactId) {
    case solvay.id:
      return solvay.name;
    case einstein.id:
      return einstein.name;
    case newton.id:
      return newton.name;
    case darwin.id:
      return darwin.name;
    default:
      return defaultName;
  }
}

export function isContactOnline(contactId: string) {
  switch (contactId) {
    // case einstein.id:
    case newton.id:
    case darwin.id:
      return true;
    default:
      return false;
  }
}

export function canLoadMessages(roomId: string) {
  return roomId === solvay.id;
}
